name: water_delivery_app
description: A water delivery application

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  http: ^1.5.0               # ✅ Correct version
  shared_preferences: ^2.2.2
  flutter_map: ^7.0.2          # ✅ Correct version
  latlong2: ^0.9.0            # ✅ Correct version
  geolocator: ^10.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
    - assets/images/logoo.jpeg
    